version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: kacper
      POSTGRES_PASSWORD: QWERTYUIOP
      POSTGRES_DB: spot_instance_comparison
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      NODE_ENV: test
      DB_USERNAME: newusername
      DB_PASSWORD: newpassword
      DB_DATABASE: database_test
      DB_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db-data:
