version: "3.8" 

volumes:
  db-data:

services:

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always 
    environment:
      - POSTGRES_PASSWORD=postgres