version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: kacper
      POSTGRES_PASSWORD: QWERTYUIOP
      POSTGRES_DB: spot_instance_comparison
    ports:
      - "5432:5432"

  test-db:
    image: postgres:16
    volumes:
      - test-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: null
      POSTGRES_DB: database_test
    ports:
      - "5433:5432" # Notice the different port

  app:
    build: .
    environment:
      NODE_ENV: development
      DB_USERNAME: kacper
      DB_PASSWORD: QWERTYUIOP
      DB_DATABASE: spot_instance_comparison
      DB_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db-data:
  test-db-data:
